# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: resque-etl 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "resque-etl"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Robert Ault"]
  s.date = "2017-09-02"
  s.description = "Edit settings for tenanted ETL."
  s.email = "rault@marketron.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.homepage = "https://github.com/rault/resque-etl"
  s.rubygems_version = "2.2.2"
  s.summary = "Edit settings for tenanted ETL."

  if s.respond_to? :specification_version then
    s.specification_version = 4
    s.files = Dir['**/*'].keep_if { |file| File.file?(file) }

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<resque>, ["= 1.27.4"])
      s.add_development_dependency(%q<rake>, ["= 10.4.2"])
      s.add_development_dependency(%q<jeweler>, ["= 2.0.1"])
      s.add_development_dependency(%q<rspec-rails>, ["= 3.1.0"])
      s.add_development_dependency(%q<rspec>, ["= 3.1.0"])
      s.add_development_dependency(%q<rack-test>, ["= 0.6.3"])
      s.add_development_dependency(%q<timecop>, ["= 0.7.1"])
      s.add_development_dependency(%q<rack>, ["= 1.5.2"])
    else
      s.add_dependency(%q<resque>, ["= 1.27.4"])
      s.add_dependency(%q<rake>, ["= 10.4.2"])
      s.add_dependency(%q<jeweler>, ["= 2.0.1"])
      s.add_dependency(%q<rspec-rails>, ["= 3.1.0"])
      s.add_dependency(%q<rspec>, ["= 3.1.0"])
      s.add_dependency(%q<rack-test>, ["= 0.6.3"])
      s.add_dependency(%q<timecop>, ["= 0.7.1"])
      s.add_dependency(%q<rack>, ["= 1.5.2"])
    end
  else
    s.add_dependency(%q<resque>, ["= 1.27.4"])
    s.add_dependency(%q<rake>, ["= 10.4.2"])
    s.add_dependency(%q<jeweler>, ["= 2.0.1"])
    s.add_dependency(%q<rspec-rails>, ["= 3.1.0"])
    s.add_dependency(%q<rspec>, ["= 3.1.0"])
    s.add_dependency(%q<rack-test>, ["= 0.6.3"])
    s.add_dependency(%q<timecop>, ["= 0.7.1"])
    s.add_dependency(%q<rack>, ["= 1.5.2"])
  end
end

